### ISSUE TITLE
Filenames are incompatible with Windows

### ISSUE THREAD

**Issue by allforabit** [hlissner/emacs-snippets#2]
When cloning to a Windows machine, the snippets with special characters don't clone correctly. Does the naming of the files impact functionality at all? If so would it be possible to rename the files. I can open a pull request if that helps? Here are the troublesome filenames:
```
error: unable to create file +php-laravel-mode/route->: Invalid argument
error: unable to create file go-mode/:=: Invalid argument
error: unable to create file lua-mode/?: Invalid argument
error: unable to create file lua-mode/self:: Invalid argument
error: unable to create file rust-mode/:: Invalid argument
error: unable to create file rust-mode/=>: Invalid argument
error: unable to create file sh-mode/<: Invalid argument
error: unable to create file sh-mode/>: Invalid argument
```

**Comment by hlissner** [comment]
File names _do_ affect functionality if the snippet has no `key` specified. E.g. `lua-mode/:=` will get triggered if you type `:=` <kbd>Tab</kbd>. You may rename them. but please add `key: ...` property to them matching their old names, e.g. `key: :=`

**Comment by allforabit** [comment]
OK thanks I will put together a pull request for that in the next few days.

**Comment by hlissner** [comment]
I've removed the illegal characters from my snippets, so I'll consider this resolved. Let me know if you discover any that I've missed.

**Comment by allforabit** [comment]
Thank you. Apologies that I didn't get around to making the pull request. I will update and let you know if I have any issues.
